# Generated by Django 3.2.6 on 2021-08-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_rater_server_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='Category', through='gamer_rater_server_api.GameCategory', to='gamer_rater_server_api.Category'),
        ),
    ]
